apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service-{{ .Release.Name }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: {{ template "app.name" . }}
    tier: {{ .Chart.Name }}
    release: {{ .Release.Name }}
