apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-app-env-{{ .Release.Name }}
data:
  SERVICE_URL: http://{{ .Chart.Name }}-service-{{ .Release.Name }}:{{ .Values.app.service.port }}
  OKAPI_URL: {{ .Values.okapi.schema }}://{{ .Values.okapi.host }}{{ with .Values.okapi.port }}:{{ . }}{{ end }}{{ .Values.okapi.path }}
  SELF_DEPLOY: "true"
  DB_HOST: {{ if .Values.db.enabled }}{{ .Chart.Name }}-db-service-{{ .Release.Name }}{{ else }}{{ .Values.app.database.host }}{{ end }}
  DB_PORT: {{ if .Values.db.enabled }}{{ .Values.db.environment.POSTGRES_PORT | default "5432" | quote }}{{ else }}{{ .Values.app.database.port | quote }}{{ end }}
  DB_USERNAME: {{ if .Values.db.enabled }}{{ .Values.db.environment.POSTGRES_USER }}{{ else }}{{ .Values.app.database.user }}{{ end }}
  DB_PASSWORD: {{ if .Values.db.enabled }}{{ .Values.db.environment.POSTGRES_PASSWORD }}{{ else }}{{ .Values.app.database.password }}{{ end }}
  DB_DATABASE: {{ if .Values.db.enabled }}{{ .Values.db.environment.POSTGRES_DB }}{{ else }}{{ .Values.app.database.db }}{{ end }}
  {{- range $index, $element := .Values.app.environment }}
  {{ $index }}: '{{ $element }}'
  {{- end }}
  {{- with .Values.proxy.no_proxy }}
  NO_PROXY: {{ $.Values.okapi.host }},{{ . }}
  no_proxy: {{ $.Values.okapi.host }},{{ . }}
  {{- end }}
  {{- with .Values.proxy.http_proxy }}
  HTTP_PROXY: {{ . }}
  http_proxy: {{ . }}
  {{- end }}
  {{- with .Values.proxy.https_proxy }}
  HTTPS_PROXY: {{ . }}
  https_proxy: {{ . }}
  {{- end }}
