apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app-{{ .Release.Name }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      tier: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        tier: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.dockerconfigjson }}
      imagePullSecrets:
      - name: registrypullsecret-{{ .Chart.Name }}-{{ .Release.Name }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-app
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-app-env-{{ .Release.Name }}
          readinessProbe:
            tcpSocket:
              port: 8081
            periodSeconds: 1
          resources:
{{ toYaml .resources | indent 12 }}
    {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
