apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-db-{{ .Release.Name }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      tier: db
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        tier: db
        release: {{ .Release.Name }}
    spec:
{{- if .Values.dockerconfigjson }}
      imagePullSecrets:
      - name: registrypullsecret-{{ .Chart.Name }}-{{ .Release.Name }}
{{- end }}
      volumes:
{{- with .Values.db.persistentVolumeClaim }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ . }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-db
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-db-env-{{ .Release.Name }}
          readinessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 1
{{- if .Values.db.persistentVolumeClaim }}
          volumeMounts:
          - mountPath: /var/lib/postgresql/data/pgdata
            name: data
{{- end }}
          resources:
{{ toYaml .Values.db.resources | indent 12 }}
    {{- with .Values.db.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.db.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.db.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
