apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db-service-{{ .Release.Name }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ template "app.name" . }}
    tier: db
    release: {{ .Release.Name }}
