{{- if .Values.dockerconfigjson -}}
apiVersion: v1
kind: Secret
metadata:
 name: registrypullsecret-{{ .Chart.Name }}-{{ .Release.Name }}
data:
 .dockerconfigjson: {{ .Values.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
