#%RAML 1.0
title: Aggregator Settings
version: v1
baseUri: http://localhost/erm-usage-harvester

documentation:
  - title: mod-erm-usage API
    content: This documents the API calls that can be made to query and manage aggregator settings

types:
  harvesterSetting: !include schemas/harvesterSetting.schema
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml
  validate: !include ./raml-util/traits/validation.raml

resourceTypes:
  collection: !include ./raml-util/rtypes/collection.raml
  collection-item: !include ./raml-util/rtypes/item-collection.raml

/erm-usage-harvester:
  /settings:
    get:
      responses:
        200:
          body:
            application/json:
              type: harvesterSetting
    post:
      body:
        application/json:
          type: harvesterSetting
  /start:
    get:
    /{id}:
      get:
  /impl:
    get:

    