#%RAML 1.0
title: mod-erm-usage-harvester API
version: v1.3
baseUri: http://localhost/erm-usage-harvester

documentation:
  - title: mod-erm-usage-harvester API
    content: This documents the API calls that can be made to mod-erm-usage-harvester

types:
  jobInfos: !include schemas/jobInfos.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml
  validate: !include ./raml-util/traits/validation.raml

resourceTypes:
  collection: !include ./raml-util/rtypes/collection.raml
  collection-item: !include ./raml-util/rtypes/item-collection.raml

/erm-usage-harvester:
  /start:
    get:
      description: Start harvesting for tenant - process all defined usage data providers
      responses:
        200:
          description: Start for tenant succeeded
          body:
            application/json:
        400:
          description: Bad request
          body:
            text/plain:
        500:
          description: Start for tenant failed
          body:
            application/json:
            text/plain:
    /{id}:
      get:
        description: Start harvesting for tenant - process a specific usage data provider only
        responses:
          200:
            description: Start for provider succeeded
            body:
              application/json:
          400:
            description: Bad request
            body:
              text/plain:
          500:
            description: Start for provider failed
            body:
              application/json:
              text/plain:
  /impl:
    get:
      description: Get available service implementations
      queryParameters:
        aggregator:
          description: Filter by 'isAggregator' property (true or false)
          type: string
          required: false
      responses:
        200:
          description: List of available service implementations
          body:
            application/json:
        400:
          description: Bad request
          body:
            text/plain:
        500:
          description: Internal server error
          body:
            text/plain:
  /jobs:
    get:
      description: Get harvesting jobs
      is: [ searchable: { description: "CQL string", example: "type==provider" }, pageable ]
      queryParameters:
        timestamp:
          description: Only return jobs created at or before this timestamp
          example: 1641020400000
          type: number
          required: false
        providerId:
          description: Only return jobs with this providerId
          example: "6697f576-78d4-4712-ae18-2612ccdcd66d"
          type: string
          required: false
      responses:
        200:
          description: List of harvesting jobs
          body:
            application/json:
              type: jobInfos
        400:
          description: Bad request
          body:
            text/plain:
        500:
            description: Internal server error
            body:
              text/plain:
    /purgefinished:
      post:
        description: Purge finished harvesting jobs
        queryParameters:
          timestamp:
            description: Only purge jobs having a timestamp less than or equal to this value
            example: 1641020400000
            type: number
        responses:
          204:
            description: Success
          400:
            description: Bad request
            body:
              text/plain:
          500:
            description: Internal server error
            body:
              text/plain:
    /purgestale:
      post:
        description: Purge stale jobs
        responses:
          204:
            description: Success
          400:
            description: Bad request
            body:
              text/plain:
          500:
            description: Internal server error
            body:
              text/plain:
    /cleanup:
      post:
        description: Perform cleanup tasks on harvesting jobs
        responses:
          204:
            description: Success
          400:
            description: Bad request
            body:
              text/plain:
          500:
            description: Internal server error
            body:
              text/plain:
